### ISSUE TITLE
Cannot add custom properties

### ISSUE THREAD

**Issue by raymondyong** [fknop/hapi-pagination#10]
Hapi-pagination appears to delete any custom properties added to the payload.  For example, it outputs:
{ 
  meta: {...},
  results: [...]
}

But I can't get it to output:
{
  meta: {...},
  results: [...],
  foo: {...}
}
-- or --
{
  meta: { foo: {...},  ... },
  results: [...]
}

**Comment by raymondyong** [comment]
https://github.com/fknop/hapi-pagination/blob/master/lib/ext.js#L192

Should append meta and results to the existing request.response.source object.

**Comment by fknop** [comment]
Indeed. Could you do a PR for this ? I'm busy at the moment and can't really do this for another week at least. Thanks.

**Comment by fknop** [comment]
Just published it. Check out the updated  documentation for `reply.paginate` method.
