### ISSUE TITLE
New feature: metadata in HTTP headers

### ISSUE THREAD

**Issue by peveuve** [fknop/hapi-pagination#27]
New feature proposal : send the metadata in the HTTP headers rather than in the body.
The advantage is to not change the payload structure for the callers, and use HTTP headers designed for this purpose.
HTTP headers to use :

- Content-Range: "`startIndex-endIndex/totalCount`"
Provides current page position and size in the overall dataset.

- Link: [
   "`<url>; rel=self`",
   "`<url>; rel=first`",
   "`<url>; rel=prev`",
   "`<url>; rel=next`",
   "`<url>; rel=last`",
]
Provides links to current, first, previous, next and last pages.

The metadata location would be configured thanks to a new option:
```
options: {
   meta: {
      location: "header" | "body"
   }
}
```

default value: "body"

I have some code ready for a pull request.

**Comment by fknop** [comment]
If you can manage to include all the existing metadata in the headers and add tests. I'm open to it.

**Comment by peveuve** [comment]
It can't be exactly the same metadata because those headers are defined in the HTTP RFC (see https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.16), but you can deduce them from simple computations.
If you give me the permission, I can push a branch with the changes and create a pull request, so you can see by yourself. I have created 2 unit tests to illustrate this.

**Comment by fknop** [comment]
Of course, I'll check the PR once it's done !

**Comment by peveuve** [comment]
so what do you think of the PR?
