### ISSUE TITLE
Add quotes around rel value for RFC compliance

### ISSUE THREAD

**Issue by wraithgar** [fknop/hapi-pagination#35]
First off I want to say thank you for making this module!  It's really great and I'm glad it exists.

I know this would be a breaking change, but what are the odds we could add quotes around the rel target?  I noticed other sites (i.e. githhub) do this, and a lot of "link header parsing" libraries expect this.  I was looking at the rfc and all the examples have quotes around the rel value too: https://tools.ietf.org/html/rfc5988

Specifically, instead of `rel=relationship` it would be `rel="relationship"`

I would be happy to attempt the PR to implement this if you think it is a good direction to go.

**Comment by fknop** [comment]
Apparently, it must be quoted if it contains ";" or ",". It doesn't say that it can't be quoted if it doesn't so I don't see any problem adding quotes.

I would be happy to accept a PR.

I don't know yet if I'll consider it a breaking change or a fix. But it's probably safer to release it a as major version.

@peveuve As you added this feature, what do you think ?

**Comment by wraithgar** [comment]
The PR was easy enough to make so I went ahead and made it, thanks for considering it.

**Comment by fknop** [comment]
Closed with #36

**Comment by peveuve** [comment]
A bit late, bit I agree with the change.

**Comment by fknop** [comment]
I decided to publish this as a minor version instead of major. I consider this change more a fix than a breaking change.
