### ISSUE TITLE
Relative URL for meta data

### ISSUE THREAD

**Issue by garbles9100** [fknop/hapi-pagination#43]
Would it be possible to add a configuration setting for getting relative URLs in the "meta" object of the response for the "next", "previous", "self", "first" and "last" keys? For example, instead of getting:
"self": "http://MyURL/MyEndpoint/?limit=1&page=2"
It would be:
"self":"MyEndpoint/?limit=1&page=2" OR "self":"/MyEndpoint/?limit=1&page=2"

**Comment by fknop** [comment]
There is already baseUri setting but it can't be empty. I could probably add some `relative` configuration to be able to do that. Or simply modify the default of baseUri to null/undefined so we could add an empty baseUri.

I'll dig into that tomorrow if I have time but probably saturday.

**Comment by garbles9100** [comment]
Sounds good. Thank you!

**Comment by fknop** [comment]
Hi!

Sorry for the delay, I've been a little busy. It should be good now!

You should be able to use `''` for baseUri and have relative urls!
