### ISSUE TITLE
Date query parameters getting stripped from meta URLs

### ISSUE THREAD

**Issue by garbles9100** [fknop/hapi-pagination#55]
When I call reply.paginate(data, totalCount) and I have a query parameter in my URL (localhost:1234/endpoint?startDate=2017-07-26) the relative URL for meta.self (and others) shows up as:
"/endpoint?startDate=&limit=20&page=1". The data I passed in for the startDate is just gone.

**Comment by fknop** [comment]
https://github.com/fknop/hapi-pagination/pull/54 Probably linked to this.

**Comment by garbles9100** [comment]
Oh yes. I missed that. Thanks!
