### ISSUE TITLE
Question: Hapi 1.17 upgrade plans, required actions?

### ISSUE THREAD

**Issue by jimutt** [fknop/hapi-pagination#62]
Looking to add some pagination to a Hapi 1.17 project but I noticed the big disclaimer: "[NOT UPDATED FOR 1.17]". Are there any plans/work being done on updating this plugin for Hapi 1.17? What changes will be required?

**Comment by fknop** [comment]
Thanks for asking, PR would be welcome, I don't really have time to update this with my studies.

I don't think it'll require too much change, but you would need to read the patch note for hapi 1.17 related to plugins.

It might even work, I didn't try it to be honest, but as Hapi 1.17 is a big breaking change update, I'm just making sure that people know that it's not updated yet if it requires changes.

**Comment by jimutt** [comment]
Alright, if I'm able to find some time I'll maybe have a look at it (no promises though). :)

**Comment by jimutt** [comment]
Got 42 tests passing now, most work is adapting all the test cases to the new async/await flow.

**Comment by microcipcip** [comment]
@jimutt I have installed the plugin and copied-pasted the options object from the readme and I got ` child "reply" fails because ["totalCount" is not allowed]`

**Comment by fknop** [comment]
Yes, I'm sorry, the README is out of date. In the meantime, you can check here the real schema here: https://github.com/fknop/hapi-pagination/blob/master/lib/config.js#L67
  
totalCount is under parameters and not directly under reply. I think this is why you have this error.

**Comment by microcipcip** [comment]
Thanks, it works now :)
