### ISSUE TITLE
Wrong or missing metadata

### ISSUE THREAD

**Issue by ferrao** [fknop/hapi-pagination#64]
I am getting some weird metadata for the query `https://localhost:8081/api/user?limit=1&page=2` on a collection of 3 elements:

```
{
    "meta": {
        "count": 1,
        "pageCount": null,
        "totalCount": null,
        "next": null,
        "previous": "https://localhost:8081/api/user?limit=1&page=1",
        "self": "https://localhost:8081/api/user?limit=1&page=2",
        "first": "https://localhost:8081/api/user?limit=1&page=1",
        "last": null
    },
    "results": [
        {
            "id": 2,
            "username": "test",          
        }
    ]
}
```
All those `null` values there just seem wrong to me. And If I set `meta.location='header'` its even worse, I get no headers whatsoever. Looking at `ext.js` I see:

```
if (totalCount > currentLimit && results.length > 0) {
   // headers are set
}
```

Considering `totalCount` always gets here `undefined` this condition always evaluates to false and hence no headers..

Am I missing something, or is `hapi-pagination` broken? If that is the case, I am happy to work on fixing it.

**Comment by fknop** [comment]
Are you using the paginate method to pass the total count?

**Comment by ferrao** [comment]
Not at all @fknop, but just realised I should, please ignore this and thank you for this nice module that is now doing exactly what I want :)

**Comment by fknop** [comment]
No problem :)
