### ISSUE TITLE
 The results must be an array

### ISSUE THREAD

**Issue by Nickynodejs** [fknop/hapi-pagination#75]
"hapi": "^18.1.0", "hapi-pagination": "^2.1.0",Operation error reporting。

Debug: internal, implementation, error
    AssertionError [ERR_ASSERTION]: The results must be an array

**Comment by Nickynodejs** [comment]
`
            try {
                const {rows:results,totalCount:totalCount} = await users.findAndCountAll({
                    where:omit(request.query,['page','limit','pagination']),
                    attributes:{exclude:['updated_at','password']},
                    limit:limit,
                    offset:(page - 1) * limit,
                    order:[
                        ['created_at','DESC']
                    ]
                });
                
                return responseClient(200,0,'用户列表',{results:results,totalCount:totalCount})
            }catch (e) {
                return responseClient()
            }
`

**Comment by Nickynodejs** [comment]
```

            try {
                const {rows:results,totalCount:totalCount} = await users.findAndCountAll({
                    where:omit(request.query,['page','limit','pagination']),
                    attributes:{exclude:['updated_at','password']},
                    limit:limit,
                    offset:(page - 1) * limit,
                    order:[
                        ['created_at','DESC']
                    ]
                });
                
                return responseClient(200,0,'用户列表',{results:results,totalCount:totalCount})
            }catch (e) {
                return responseClient()
            }

```

**Comment by wisdomQiuqiu** [comment]
I have same problem。。。。how to resolve this problem。。。。"@hapi/hapi": "^18.4.0","hapi-pagination": "^3.0.0"

**Comment by faustbrian** [comment]
@wisdomQiuqiu What does your response look like? You should have something like `return { results: [], totalCount: 10 }` in your method.

**Comment by wisdomQiuqiu** [comment]
this is my code
`const {
        rows: results,
        count: totalCount
      } = await models.shops.findAndCountAll({
        attributes: ["id", "name"],
        limit: request.query.limit,
        offset: (request.query.page - 1) * request.query.limit
      });
      return {
        code: 200,
        content: {
          currentList: results,
          totalCount
        }
      };`

**Comment by wisdomQiuqiu** [comment]
What causes this problem？？

**Comment by faustbrian** [comment]
Based on that code it should look more like this.

```js
const { rows: results, count: totalCount } = await models.shops.findAndCountAll({
    attributes: ["id", "name"],
    limit: request.query.limit,
    offset: (request.query.page - 1) * request.query.limit
});

return { results, totalCount };
```

The `results` and `totalCount` properties have to be at the root of the response.

**Comment by wisdomQiuqiu** [comment]
How do i want to nest one more layer？？

**Comment by faustbrian** [comment]
You can't but you can add custom properties. Just read the documentation for https://github.com/fknop/hapi-pagination#hpaginatearrayobject-totalcount-options--.

**Comment by wisdomQiuqiu** [comment]
ok，thank you
