### ISSUE TITLE
totalCount and pageCount values when result set is empty

### ISSUE THREAD

**Issue by richardlay** [fknop/hapi-pagination#8]
If an empty result set is returned, i.e. `reply.paginate([], 0)`, totalCount and pageCount are null. Should these be set to 0?

**Comment by fknop** [comment]
Indeed, that would make more sense. I'll do that later when I have time, or I'll accept another PR :).

**Comment by richardlay** [comment]
Yep I can do it. Just wanted to ask first. Thanks.

**Comment by fknop** [comment]
> Yep I can do it. Just wanted to ask first. Thanks.

It's already done, but thanks !
